{{- if .Values.issuer.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-cloudflare-api
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: {{ .Values.issuer.token }}
{{- end }}
