{{- if .Values.issuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: letsencrypt-cloudflare-private-key
    server: {{ .Values.issuer.server }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-cloudflare-api
              key: CLOUDFLARE_API_TOKEN
{{- end }}
