apiVersion: v2
name: rclone-csi-controller
version: 1.0.0

dependencies:
  - repository: oci://ghcr.io/veloxpack/charts
    name: csi-driver-rclone
    version: 0.4.7
    alias: rclone-csi-driver
    condition: rclone-csi-driver.enabled
