apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: victoria-metrics-storage
spec:
  template:
    type: Opaque
  encryptedData:
    remote: {{ .Values.secrets.REMOTE_NAME | quote }}
    configData: {{ .Values.secrets.REMOTE_CONFIGURATION_DATA | quote }}
