apiVersion: v2
name: traefik
version: 1.0.0

dependencies:
  - name: traefik-crds
    repository: https://traefik.github.io/charts
    version: 1.13.1
    alias: traefik
    condition: traefik.enabled
