cluster:
  server: https://kubernetes.default.svc

ingress:
  enabled: true
  hosts:
    - argocd.dev.{{ .Values.global.metadata.domain }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  tls:
    enabled: false
