apiVersion: v2
name: victoria-metrics-operator
version: 1.0.0

dependencies:
  - repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-operator-crds
    version: 26.0.1
  - repository: https://victoriametrics.github.io/helm-charts
    name: victoria-metrics-operator
    alias: victoria-metrics
    version: 0.58.1
