victoria-metrics:
  vmsingle:
    spec:
      retentionPeriod: 7d
      storage:
        storageClassName: local-path
  grafana:
    ingress:
      enabled: true
      hosts:
        # These need to be overwritten manually, since templating is not supported in every usage sadly.
        - grafana.localhost
      tls:
        - hosts:
            # These need to be overwritten manually, since templating is not supported in every usage sadly.
            - grafana.localhost
          secretName: grafana-crt
